apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes   # relative to the Git repo root
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-homelab
    namespace: flux-system
  wait: true
  timeout: 2m
