apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../repos      # HelmRepository definitions
  - ../../apps       # All your apps (each must have its own kustomization.yaml)
