apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-homelab
    namespace: flux-system
  timeout: 2m
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repos
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-homelab
    namespace: flux-system
  timeout: 2m
  wait: true
