# 
# kjstomization custom resource to load resources located in the apps folder
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./shared/repos 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system