---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cilium
resources:
  - namespace.yaml
  - ./helmrelease.yaml
  
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=./values.yaml
configurations:
  - ./kustomizeconfig.yaml